# Generated by Django 3.1.7 on 2021-05-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productreview_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='name',
            new_name='person',
        ),
    ]
