# Generated by Django 3.1.7 on 2021-04-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent',
        ),
    ]
